flowchart TD
  User -- requests page --> WebApp
  WebApp -- requests data --> LiturgicalEngine
  LiturgicalEngine -- gets storage --> storageFactory
  storageFactory -- provides --> IStorageService
  IStorageService -- queries --> Database
  Database -- returns data --> IStorageService
  IStorageService -- returns data --> LiturgicalEngine
  LiturgicalEngine -- processes data --> WebApp
  WebApp -- renders UI --> User
